/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardUsersIndexRouteImport } from './routes/_dashboard/users/index'
import { Route as DashboardLessonsIndexRouteImport } from './routes/_dashboard/lessons/index'
import { Route as StudentLessonsLessonIdRouteImport } from './routes/student/lessons/$lessonId'
import { Route as ApiSyncSplatRouteImport } from './routes/api/sync/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAnalyticsIngestRouteImport } from './routes/api/analytics/ingest'
import { Route as DashboardUsersCreateRouteImport } from './routes/_dashboard/users/create'
import { Route as DashboardLessonsCreateRouteImport } from './routes/_dashboard/lessons/create'
import { Route as DashboardLessonsLessonIdRouteImport } from './routes/_dashboard/lessons/$lessonId'
import { Route as DashboardUsersUserIdEditRouteImport } from './routes/_dashboard/users/$userId.edit'
import { Route as DashboardLessonsLessonIdEditRouteImport } from './routes/_dashboard/lessons/$lessonId.edit'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLessonsIndexRoute = DashboardLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => DashboardRoute,
} as any)
const StudentLessonsLessonIdRoute = StudentLessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => StudentRoute,
} as any)
const ApiSyncSplatRoute = ApiSyncSplatRouteImport.update({
  id: '/api/sync/$',
  path: '/api/sync/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsIngestRoute = ApiAnalyticsIngestRouteImport.update({
  id: '/api/analytics/ingest',
  path: '/api/analytics/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersCreateRoute = DashboardUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLessonsCreateRoute = DashboardLessonsCreateRouteImport.update({
  id: '/lessons/create',
  path: '/lessons/create',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/lessons/create.lazy').then((d) => d.Route),
)
const DashboardLessonsLessonIdRoute =
  DashboardLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/lessons/$lessonId.lazy').then((d) => d.Route),
  )
const DashboardUsersUserIdEditRoute =
  DashboardUsersUserIdEditRouteImport.update({
    id: '/users/$userId/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLessonsLessonIdEditRoute =
  DashboardLessonsLessonIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardLessonsLessonIdRoute,
  } as any).lazy(() =>
    import('./routes/_dashboard/lessons/$lessonId.edit.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/student': typeof StudentRouteWithChildren
  '/student/': typeof StudentIndexRoute
  '/lessons/$lessonId': typeof DashboardLessonsLessonIdRouteWithChildren
  '/lessons/create': typeof DashboardLessonsCreateRoute
  '/users/create': typeof DashboardUsersCreateRoute
  '/api/analytics/ingest': typeof ApiAnalyticsIngestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sync/$': typeof ApiSyncSplatRoute
  '/student/lessons/$lessonId': typeof StudentLessonsLessonIdRoute
  '/lessons/': typeof DashboardLessonsIndexRoute
  '/users/': typeof DashboardUsersIndexRoute
  '/lessons/$lessonId/edit': typeof DashboardLessonsLessonIdEditRoute
  '/users/$userId/edit': typeof DashboardUsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/': typeof DashboardIndexRoute
  '/student': typeof StudentIndexRoute
  '/lessons/$lessonId': typeof DashboardLessonsLessonIdRouteWithChildren
  '/lessons/create': typeof DashboardLessonsCreateRoute
  '/users/create': typeof DashboardUsersCreateRoute
  '/api/analytics/ingest': typeof ApiAnalyticsIngestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sync/$': typeof ApiSyncSplatRoute
  '/student/lessons/$lessonId': typeof StudentLessonsLessonIdRoute
  '/lessons': typeof DashboardLessonsIndexRoute
  '/users': typeof DashboardUsersIndexRoute
  '/lessons/$lessonId/edit': typeof DashboardLessonsLessonIdEditRoute
  '/users/$userId/edit': typeof DashboardUsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/student': typeof StudentRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/student/': typeof StudentIndexRoute
  '/_dashboard/lessons/$lessonId': typeof DashboardLessonsLessonIdRouteWithChildren
  '/_dashboard/lessons/create': typeof DashboardLessonsCreateRoute
  '/_dashboard/users/create': typeof DashboardUsersCreateRoute
  '/api/analytics/ingest': typeof ApiAnalyticsIngestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sync/$': typeof ApiSyncSplatRoute
  '/student/lessons/$lessonId': typeof StudentLessonsLessonIdRoute
  '/_dashboard/lessons/': typeof DashboardLessonsIndexRoute
  '/_dashboard/users/': typeof DashboardUsersIndexRoute
  '/_dashboard/lessons/$lessonId/edit': typeof DashboardLessonsLessonIdEditRoute
  '/_dashboard/users/$userId/edit': typeof DashboardUsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/student'
    | '/student/'
    | '/lessons/$lessonId'
    | '/lessons/create'
    | '/users/create'
    | '/api/analytics/ingest'
    | '/api/auth/$'
    | '/api/sync/$'
    | '/student/lessons/$lessonId'
    | '/lessons/'
    | '/users/'
    | '/lessons/$lessonId/edit'
    | '/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/student'
    | '/lessons/$lessonId'
    | '/lessons/create'
    | '/users/create'
    | '/api/analytics/ingest'
    | '/api/auth/$'
    | '/api/sync/$'
    | '/student/lessons/$lessonId'
    | '/lessons'
    | '/users'
    | '/lessons/$lessonId/edit'
    | '/users/$userId/edit'
  id:
    | '__root__'
    | '/_dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/student'
    | '/_dashboard/'
    | '/student/'
    | '/_dashboard/lessons/$lessonId'
    | '/_dashboard/lessons/create'
    | '/_dashboard/users/create'
    | '/api/analytics/ingest'
    | '/api/auth/$'
    | '/api/sync/$'
    | '/student/lessons/$lessonId'
    | '/_dashboard/lessons/'
    | '/_dashboard/users/'
    | '/_dashboard/lessons/$lessonId/edit'
    | '/_dashboard/users/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  StudentRoute: typeof StudentRouteWithChildren
  ApiAnalyticsIngestRoute: typeof ApiAnalyticsIngestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSyncSplatRoute: typeof ApiSyncSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users/': {
      id: '/_dashboard/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/lessons/': {
      id: '/_dashboard/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof DashboardLessonsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/student/lessons/$lessonId': {
      id: '/student/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/student/lessons/$lessonId'
      preLoaderRoute: typeof StudentLessonsLessonIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/api/sync/$': {
      id: '/api/sync/$'
      path: '/api/sync/$'
      fullPath: '/api/sync/$'
      preLoaderRoute: typeof ApiSyncSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/ingest': {
      id: '/api/analytics/ingest'
      path: '/api/analytics/ingest'
      fullPath: '/api/analytics/ingest'
      preLoaderRoute: typeof ApiAnalyticsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/users/create': {
      id: '/_dashboard/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof DashboardUsersCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/lessons/create': {
      id: '/_dashboard/lessons/create'
      path: '/lessons/create'
      fullPath: '/lessons/create'
      preLoaderRoute: typeof DashboardLessonsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/lessons/$lessonId': {
      id: '/_dashboard/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof DashboardLessonsLessonIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users/$userId/edit': {
      id: '/_dashboard/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof DashboardUsersUserIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/lessons/$lessonId/edit': {
      id: '/_dashboard/lessons/$lessonId/edit'
      path: '/edit'
      fullPath: '/lessons/$lessonId/edit'
      preLoaderRoute: typeof DashboardLessonsLessonIdEditRouteImport
      parentRoute: typeof DashboardLessonsLessonIdRoute
    }
  }
}

interface DashboardLessonsLessonIdRouteChildren {
  DashboardLessonsLessonIdEditRoute: typeof DashboardLessonsLessonIdEditRoute
}

const DashboardLessonsLessonIdRouteChildren: DashboardLessonsLessonIdRouteChildren =
  {
    DashboardLessonsLessonIdEditRoute: DashboardLessonsLessonIdEditRoute,
  }

const DashboardLessonsLessonIdRouteWithChildren =
  DashboardLessonsLessonIdRoute._addFileChildren(
    DashboardLessonsLessonIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLessonsLessonIdRoute: typeof DashboardLessonsLessonIdRouteWithChildren
  DashboardLessonsCreateRoute: typeof DashboardLessonsCreateRoute
  DashboardUsersCreateRoute: typeof DashboardUsersCreateRoute
  DashboardLessonsIndexRoute: typeof DashboardLessonsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardUsersUserIdEditRoute: typeof DashboardUsersUserIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLessonsLessonIdRoute: DashboardLessonsLessonIdRouteWithChildren,
  DashboardLessonsCreateRoute: DashboardLessonsCreateRoute,
  DashboardUsersCreateRoute: DashboardUsersCreateRoute,
  DashboardLessonsIndexRoute: DashboardLessonsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardUsersUserIdEditRoute: DashboardUsersUserIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface StudentRouteChildren {
  StudentIndexRoute: typeof StudentIndexRoute
  StudentLessonsLessonIdRoute: typeof StudentLessonsLessonIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentIndexRoute: StudentIndexRoute,
  StudentLessonsLessonIdRoute: StudentLessonsLessonIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  StudentRoute: StudentRouteWithChildren,
  ApiAnalyticsIngestRoute: ApiAnalyticsIngestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSyncSplatRoute: ApiSyncSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
